name: GitHub Actions CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: get commit message
      run: |
        echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
    - name: show commit message
      run : echo $commitmsg           
    - name: Install submodules 
      run: |        
        pwd
        git submodule update --init
        ls
    - name: Set lib extra dirs for CI
      run: |        
        sed -i 's,^lib_extra_dirs =.*$,lib_extra_dirs = /home/runner/work/arduino_bootstrapper/arduino_bootstrapper/arduino_bootstrapper,' platformio.ini
        cat platformio.ini
    - name: Run PlatformIO
      run: platformio run -e bootstrapper
    - name: Creating artifact from BIN file
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_arduino_bootstrapper.bin
        path: .pio/build/bootstrapper/firmware.bin

# on:
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# name: Create Release

# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: get commit message
#         run: |
#            echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
#       - name: show commit message
#         run : echo $commitmsg        
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false        