name: GitHub Actions CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version         
    - name: Install submodules 
      run: |        
        pwd
        git submodule update --init
        ls
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2         
    - name: Static code analysis
      run: platformio check --verbose --severity=high --skip-packages                     
    - name: Run PlatformIO
      run: platformio run -e bootstrapper
    - name: Creating artifact from BIN file
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_arduino_bootstrapper.bin
        path: .pio/build/bootstrapper/firmware.bin